
// http://jenkins:8080/pipeline-syntax/globals#params

pipeline {
    
    agent any
    /*
    agent {
        label 'cliente1'
    }
    */
    
    stages {
        stage('Stage init') {
            steps {
                println "Hello from stage init"
            }
        }
    }
    
    post {
        always {
            script {
                // Obtener y mostrar la información de los parámetros
                def paramsInfo = params.collect { param ->
                    "${param.key}: ${param.value}"
                }
                
                println "Información de los parámetros:"
                println paramsInfo.join('\n')
            }
        }
    }
}