
// http://jenkins:8080/pipeline-syntax/globals#env

pipeline {
    
    /*
    agent {
        label 'cliente1'
    }
    */
    
    stages {
        stage('Stage init') {
            steps {
                println "Hello from stage init"
            }
        }
    }
    
    post {
        always {
            script {
                /*
                echo "BUILD_NUMBER: $BUILD_NUMBER"
                echo "JOB_NAME: $JOB_NAME"
                echo "BUILD_ID: $BUILD_ID"
                echo "NODE_NAME: $NODE_NAME"
                echo "BUILD_URL: $BUILD_URL"
                echo "WORKSPACE: $WORKSPACE"
                echo "GIT_BRANCH: $GIT_BRANCH"              
                echo "EXECUTOR_NUMBER: $EXECUTOR_NUMBER"
                echo "BUILD_TAG: $BUILD_TAG"
                echo "BUILD_DISPLAY_NAME: $BUILD_DISPLAY_NAME"
                echo "JENKINS_HOME: $JENKINS_HOME"
                echo "JENKINS_URL: $JENKINS_URL"
                echo "JOB_URL: $JOB_URL"
                echo "WORKSPACE_TMP: $WORKSPACE_TMP"
                */

                println "BUILD_NUMBER: ${env.BUILD_NUMBER}"
                println "JOB_NAME: ${env.JOB_NAME}"
                println "BUILD_ID: ${env.BUILD_ID}"
                println "NODE_NAME: ${env.NODE_NAME}"
                println "BUILD_URL: ${env.BUILD_URL}"
                println "WORKSPACE: ${env.WORKSPACE}"                
            }
        }
    }
}