import jenkins.model.*

collectBuildEnv = [:] // empty map

@NonCPS
def getNodes(String label) {
    jenkins.model.Jenkins.instance.nodes.collect { thisAgent ->
        if (thisAgent.labelString.contains("${label}")) {
            return thisAgent.name
        }
    }
}

def dumpBuildEnv(String agentName) {
    node("${agentName}") {
        stage("Env in ${agentName}") {
            echo "running on agent, ${agentName}"
            sh 'sleep 10'
        }
    }
}

def processTask() {
    def nodeList = getNodes("linux")
    
    for(i=0; i<nodeList.size(); i++) {
        def agentName = nodeList[i]
        
        if (agentName != null) {
            println "Preparing task for " + agentName
            collectBuildEnv["node_" + agentName] = {
                dumpBuildEnv(agentName)
            }
        }
    }
}

pipeline {
    // dedicated node to execute this admin tasks
    agent {
        label "cliente2"
    }

        
    stages {
        stage('agents-tasks') {
            
            steps {
                script {
                    processTask()
      
                    parallel collectBuildEnv
                }
            }
        }
    }
}
