pipeline {
    agent any
    
    stages {
        stage('Imprimir agentes con etiqueta') {
            steps {
                script {
                    def label = 'linux'
                    def nodes = Jenkins.instance.nodes.findAll { node -> node.getLabelString().contains(label) }

                    nodes.each { node ->
                        echo "Agente con etiqueta '${label}': ${node.getDisplayName()}"
                        echo "Direccion IP: ${node.computer.hostName}"

                    }
                }
            }
        }
    }
}


/*
http://jenkins:8080/scriptApproval/

Signatures already approved:

method hudson.model.AbstractCIBase getNodes
method hudson.model.Computer getHostName
method hudson.model.Node getLabelString
method hudson.model.Slave getComputer
staticMethod jenkins.model.Jenkins getInstance

*/
