pipeline {
    agent none
    stages {
        stage('Stage 1') {
            agent { label 'linux' }
            steps {
                sh "hostname"
                echo "HelloWorld from stage 1"
            }
        }
        stage('Stage 2') {
            agent { label 'linux' }
            steps {
                sh "hostname"
                echo "HelloWorld from stage 2"
                sleep 10
            }
        }
        stage('Stage 3') {
            agent { label 'linux' }
            steps {
                sh "hostname"
                echo "HelloWorld from stage 3"
            }
        }        
    }
}

