pipeline {
    agent none
    stages {
        stage('Stage 1') {
            agent { label 'linux' }
            steps {
                sh "hostname"
                echo "HelloWorld from stage 1"
            }
        }
        stage('Stage 2') {
            agent { label 'linux' }
            steps {
                sh "hostname"
                echo "HelloWorld from stage 2"
                sleep 10
            }
        }
        stage('Stage 3') {
            agent { label 'linux' }
            steps {
                sh "hostname"
                echo "HelloWorld from stage 3"
            }
        }    
        stage('Stage 4: call script') {
            agent { label 'linux' }
            steps {
                powershell '''
                ./Freestyle/hostname.ps1
                '''
                echo "HelloWorld from stage 4"
            }
        }  

    }
}

