pipeline {

    // agent any
    
    // dedicated node to execute this admin tasks
    agent {
        label "cliente2"
    }    

    stages {
        stage('Stage1') {
            steps {
                script {
                    parallelTasks()
                }
            }
        }
    }
}


def parallelTasks() {
    def labels = ['cliente1', 'cliente2'] 
    def builders = [:]
    for (x in labels) {
        // Bind the label variable before the closure - (label in labels) = ERROR'
        def label = x 

        // Create a map to pass-in to the 'parallel' step so we can fire all the builds at once
        builders[label] = {
            node(label) {
                currentBuild.displayName = "${BUILD_ID} - ${JOB_NAME} - ${NODE_NAME}"
                sh '''
                echo "hostname:`hostname`"
                echo "whoami:`whoami`"
                sleep 10
                '''
            }
        }
    }
    parallel builders
}
