pipeline {

    agent any

    stages {
        stage('Stage1') {
            steps {
                script {
                    parallelTasks()
                }
            }
        }
    }
}

def parallelTasks() {
    def labels = ['cliente1', 'cliente2'] // labels for Jenkins node types we will build on
    def builders = [:]
    for (x in labels) {
        def label = x // Need to bind the label variable before the closure - can't do 'for (label in labels)'

        // Create a map to pass in to the 'parallel' step so we can fire all the builds at once
        builders[label] = {
            node(label) {
                sh '''
                echo "hostname:`hostname`"
                echo "whoami:`whoami`"
                sleep 10
                '''
            }
        }
    }
    parallel builders
}
